version: '3.9'

volumes:
  db-data:

services:
  base: &base
    image: node:18.16.0-alpine
    working_dir: /home/node/app
    stdin_open: true
    tty: true
    env_file:
      - .env

  api:
    <<: *base
    hostname: mc-api
    command: ash -c "yarn && yarn dev"
    environment:
      EXPRESS_PORT: ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/home/node/app

  db:
    image: postgres:15.3
    hostname: mc-db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
